### ISSUE TITLE
Unable to generate HTML report

### ISSUE THREAD

**Issue by anshul-discovery** [deadlydexter/Ruby-Cucumber-Framework-using-CircleCI#3]
I tried your approach to generate HTML report but it's not getting generated instead of that I'm facing an error which is mentioned below

`No such file or directory @ rb_sysopen - /home/circleci/Project/test_results/features_report.html
Error creating formatter: html (Errno::ENOENT)`

If you can help me it would be great please. My email is anshultyagi90@gmail.com

**Comment by deadlydexter** [comment]
@anshul-discovery Please make sure that the destination directory exists prior to trying to save the html file in this location i.e., "/home/circleci/Project/test_results/" or you can use "--out cucumberReport.html" in your cucumber.yml file which will generate the report in its root directory.

**Comment by anshul-discovery** [comment]
I'm trying like

           `mkdir -p ~/cucumber
            bundle exec cucumber --format pretty --out CucumberReport.html

      # Save test results for timing analysis
      - store_test_results:
          path: ~/cucumber/test_results
      - store_artifacts:
          path: ~/cucumber/test_results`

but still no luck.

Error is 
    
`No such file or directory - features. You can use `cucumber --init` to get started.

`Exited with code exit status 2
CircleCI received exit code 2`

**Comment by deadlydexter** [comment]
sorry for the late reply,

I had made some code changes to cucumber.yml file, to execute using rake task use following steps :

Open terminal and type "rake ui_tests"
This command will run the cucumber profile "ui_tests" from the cucumber.yml file.
that is the following cucumber profile
ui_tests: --no-source --color --format pretty --tags @AdoptingOnePuppy --format html --out cucumberReport.html

Additionally you can set destination path where you want to generate file in above command.

Please let me know if this resolved this issue :)
